import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/components/CartProvider";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "React App",
  description: "Generated by React App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        <CartProvider>
          <Navbar />
          <main className="container mx-auto p-2">{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
